---

- hosts: all

  tasks:
    - name: Add pacman repos
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [pritunl]
          Server = https://repo.pritunl.com/stable/pacman
      become: yes

    - name: Add pacman keys
      shell: |
        pacman-key --keyserver hkps://hkps.pool.sks-keyservers.net:443 -r 7568D9BB55FF9E5287D586017AE645C0CF8E292A \
        && pacman-key --lsign-key 7568D9BB55FF9E5287D586017AE645C0CF8E292A
      become: yes

    - pacman:
        state: latest
        update_cache: yes
        name:
          - neovim
          - emacs
          - telegram-desktop
          - ripgrep
          - zsh
          - fzf
          - tmux
          - tig
          - jq
          - lsd
          - fd
          - alacritty
          - kitty
          - xsel
          - htop
          - adobe-source-code-pro-fonts
          - python-pip
          - lsof
          - rlwrap  # for clj
          - binutils  # for makepkg
          - gcc  # for makepkg
          - base-devel  # various build tool
          - xorg-xinit  # for xinitrc
          - transmission-gtk
          - pritunl-client-electron
          - pritunl-client-electron-numix-theme
          - pygtk  # for deluge
          - deluge  # torrent
          - docker
          - docker-compose
      become: yes

    - name: "install Yay"
      args:
        creates: /usr/bin/yay
      shell: |
        cd /tmp/ \
        && rm -rf yay/ \
        && git clone https://aur.archlinux.org/yay.git \
        && cd yay/ \
        && makepkg -si --noconfirm \
        && cd ../ \
        && rm -rf yay/

    - name: "Yay"
      shell: |
        yay -S --noconfirm --needed \
          debtap \
          google-chrome \
          antibody

    - pip:
        extra_args: "--user"
        state: latest
        name:
          - ansible-lint
          - yamllint
