---

- hosts: all

  tasks:
    - name: Add pacman repos
      blockinfile:
        path: /etc/pacman.conf
        block: |
          [pritunl]
          Server = https://repo.pritunl.com/stable/pacman
      become: yes

    - name: Add pacman keys
      shell: |
        pacman-key --keyserver hkp://keyserver.ubuntu.com -r 7568D9BB55FF9E5287D586017AE645C0CF8E292A \
        && pacman-key --lsign-key 7568D9BB55FF9E5287D586017AE645C0CF8E292A
      become: yes

    - pacman:
        state: latest
        update_cache: yes
        name:
          - neovim
          - emacs
          - telegram-desktop
          - ripgrep
          - zsh
          - fzf
          - tmux
          - tig
          - jq
          - kitty
          - xsel
          - adobe-source-code-pro-fonts
          - lsof
          - transmission-gtk
          - pritunl-client-electron
          - pritunl-client-electron-numix-theme
      become: yes

    - name: "install Yay"
      args:
        creates: /usr/bin/yay
      shell: |
        cd /tmp/ \
        && rm -rf yay/ \
        && git clone https://aur.archlinux.org/yay.git \
        && cd yay/ \
        && makepkg -si --noconfirm \
        && cd ../ \
        && rm -rf yay/

    - name: "Yay"
      shell: |
        yay -S --noconfirm \
          debtap \
          google-chrome

    - pip:
        extra_args: "--user"
        state: latest
        name:
          - pylint
          - ansible-lint
          - yamllint
