---

- hosts: all

  tasks:
    - pacman:
        state: latest
        update_cache: true
        name:
          - neovim
          - emacs
          - telegram-desktop
          - ripgrep
          - zsh
          - fzf
          - tmux
          - tig
          - jq
          - lsd
          - bat
          - fd
          - alacritty
          - kitty
          - xsel
          - htop
          - hub
          - adobe-source-code-pro-fonts
          - python-pip
          - lsof
          - rlwrap  # for clj
          - binutils  # for makepkg
          - gcc  # for makepkg
          - base-devel  # various build tool
          - xorg-xinit  # for xinitrc
          - transmission-gtk
          - deluge  # torrent
          - docker
          - docker-compose
          - noto-fonts-emoji
          - keychain
          - dnsutils
          - traceroute
          - kubectl
          - kubectx
          - k9s
          - github-cli
      become: true
      tags: pacman

    - name: "install Yay"
      args:
        creates: /usr/bin/yay
      shell: |
        cd /tmp/ \
        && rm -rf yay/ \
        && git clone https://aur.archlinux.org/yay.git \
        && cd yay/ \
        && makepkg -si --noconfirm \
        && cd ../ \
        && rm -rf yay/

    - name: "Yay"
      shell: |
        yay -S --noconfirm --needed \
          debtap \
          google-chrome \
          antibody \
          asdf-vm

    - name: "asdf-vm autocomplete"
      shell: source /opt/asdf-vm/asdf.sh

    - name: "asdf-vm autocomplete"
      shell: source /opt/asdf-vm/asdf.sh

    - name: "asdf-vm plugins"
      shell: |
         asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git || true && \
         asdf plugin-add ruby || true && \
         asdf plugin-add golang || true && \
         asdf plugin-add python || true && \
         asdf plugin-add java || true

    - name: "asdf-vm versions"
      shell: |
         asdf install nodejs latest && \
         asdf global nodejs latest

    - pip:
        extra_args: "--user"
        state: latest
        name:
          - ansible-lint
          - yamllint
