---
- hosts: all

  vars:
    term: xterm-256color

  tasks:
    - name: Install fzf
      become: yes
      shell: |
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf \
        && ~/.fzf/install --key-bindings --update-rc --completion \
        && cp ~/.fzf/bin/fzf /usr/local/bin
      args:
        creates: /usr/local/bin/fzf
      environment:
        TERM: "{{ term }}"

    - name: Install oh-my-zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: ~/.oh-my-zsh/

    - name: Install antibody
      shell: "curl -sL git.io/antibody | sh -s"
      args:
        creates: /usr/local/bin/antibody

    - name: Setup asdf
      git:
        repo: "https://github.com/asdf-vm/asdf.git"
        dest: ~/.asdf
        version: v0.7.1

    - name: Set shell
      become: yes
      shell: "chsh -s $(which zsh);"
