---
- hosts: all

  vars:
    term: xterm-256color

  tasks:
    - name: Install fzf
      become: yes
      shell: |
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf \
        && ~/.fzf/install --key-bindings --update-rc --completion \
        && cp ~/.fzf/bin/fzf /usr/local/bin
      args:
        creates: /usr/local/bin/fzf
      environment:
        TERM: "{{ term }}"

    - name: Setup TPM
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: ~/.tmux/plugins/tpm

    - name: Setup asdf
      git:
        repo: "https://github.com/asdf-vm/asdf.git"
        dest: ~/.asdf

    - name: Set shell
      become: yes
      shell: "chsh -s $(which zsh);"
