---
- hosts: all
  tasks:

    - name: Zsh
      file:
        src: "{{ playbook_dir }}/files/zshrc_common"
        dest: ~/.zshrc
        force: yes
        state: link

    - name: Neovim
      file:
        dest: ~/.config/nvim
        force: yes
        state: directory

    - file:
        src: "{{ playbook_dir }}/files/vimrc"
        dest: ~/.config/nvim/init.vim
        force: yes
        state: link

    - name: Tmux
      file:
        src: "{{ playbook_dir }}/files/tmux.conf"
        dest: ~/.tmux.conf
        force: yes
        state: link

    - name: Alacritty config
      file:
        src: "{{ playbook_dir }}/files/alacritty.toml"
        dest: ~/.alacritty.toml
        force: yes
        state: link

    - name: Tig
      file:
        src: "{{ playbook_dir }}/files/tigrc"
        dest: ~/.tigrc
        state: link
        force: yes

    - name: Git
      file:
        src: "{{ playbook_dir }}/files/gitconfig"
        dest: ~/.gitconfig
        state: link
        force: yes

    - file:
        path: ~/.config/gitui
        state: directory
        force: yes

    - name: Gitui key bindings
      file:
        src: "{{ playbook_dir }}/files/gitui-key-bindings.ron"
        dest: ~/.config/gitui/key_bindings.ron
        state: link
        force: yes

    - name: Gitui theme
      file:
        src: "{{ playbook_dir }}/files/gitui-theme.ron"
        dest: ~/.config/gitui/theme.ron
        state: link
        force: yes


