---
- hosts: all
  tasks:

    - name: Zsh
      file:
        src: "{{ playbook_dir }}/files/zshrc_common"
        dest: ~/.zshrc
        force: yes
        state: link

    - name: Neovim
      file:
        dest: ~/.config/nvim
        force: yes
        state: directory

    - file:
        src: "{{ playbook_dir }}/files/vimrc"
        dest: ~/.config/nvim/init.vim
        force: yes
        state: link

    - name: Tmux
      file:
        src: "{{ playbook_dir }}/files/tmux.conf"
        dest: ~/.tmux.conf
        force: yes
        state: link

    - name: Spacemacs
      file:
        src: "{{ playbook_dir }}/files/spacemacs"
        dest: ~/.spacemacs
        force: yes
        state: link

    - name: xprofile
      file:
        src: "{{ playbook_dir }}/files/xprofile"
        dest: ~/.xprofile
        force: yes
        state: link

    - name: Xmodemap
      file:
        src: "{{ playbook_dir }}/files/xmodemap"
        dest: ~/.Xmodemap
        force: yes
        state: link

    - file:
        dest: ~/.config/kitty/
        state: directory

    - file:
        src: "{{ playbook_dir }}/files/kitty.conf"
        dest: ~/.config/kitty/kitty.conf
        state: link
        force: yes

    - name: Tig
      file:
        src: "{{ playbook_dir }}/files/tigrc"
        dest: ~/.tigrc
        state: link
        force: yes

    - name: Git
      file:
        src: "{{ playbook_dir }}/files/gitconfig"
        dest: ~/.gitconfig
        state: link
        force: yes
