---
- hosts: all
  vars:
    config: ~/.bash_profile
  tasks:

    - file:
        dest: ~/.config/nvim
        state: directory

    - file:
        src: "{{ playbook_dir }}/files/vimrc"
        dest: ~/.config/nvim/init.vim
        state: link

    - file:
        path: ~/.local/share/nvim/site/autoload
        state: directory
        recurse: Yes

    - name: Install vim plug
      shell: 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      args:
        creates: ~/.local/share/nvim/site/autoload/plug.vim

    - name: Coc
      file:
        src: "{{ playbook_dir }}/files/coc-settings.json"
        dest: ~/.config/nvim/coc-settings.json
        state: link

    - file:
        src: "{{ playbook_dir }}/files/vimrc"
        dest: ~/.config/nvim/init.vim
        state: link
    - name: Install vim deps
      shell: "nvim -E -s -V -u ~/.config/nvim/init.vim +PlugInstall +qall || true"

    - name: Install spacemacs
      git:
        repo: "https://github.com/syl20bnr/spacemacs"
        dest: ~/.emacs.d
        version: develop

    - file:
        src: "{{ playbook_dir }}/files/spacemacs"
        dest: ~/.spacemacs
        state: link
