---
- hosts: all
  vars:
    config: ~/.bash_profile
  tasks:

    - file:
        dest: ~/.config/nvim
        state: directory

    - file:
        src: "{{ playbook_dir }}/files/vimrc"
        dest: ~/.config/nvim/init.vim
        state: link

    - file:
        path: ~/.local/share/nvim/site/autoload
        state: directory
        recurse: Yes

    - get_url:
        force: yes
        dest: ~/.local/share/nvim/site/autoload/plug.vim
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

    - file:
        src: "{{ playbook_dir }}/files/vimrc"
        dest: ~/.config/nvim/init.vim
        state: link

    - name: Install spacemacs
      git:
        repo: "https://github.com/syl20bnr/spacemacs"
        dest: ~/.emacs.d

    - file:
        src: "{{ playbook_dir }}/files/spacemacs"
        dest: ~/.spacemacs
        state: link
