---
- hosts: all
  tasks:

    - file:
        dest: ~/.config/kitty/
        state: directory

    - file:
        src: "{{ playbook_dir }}/files/kitty.conf"
        dest: ~/.config/kitty/kitty.conf
        state: link
        force: yes

    - name: Download kitty
      get_url:
        url: https://sw.kovidgoyal.net/kitty/installer.sh
        dest: /tmp/kitty-installer.sh
        mode: 0755

    - name: Install kitty
      command: /tmp/kitty-installer.sh

