---
- hosts: all
  tasks:
    - homebrew:
        state: present
        name:
          - readline
          - wget
          - zsh
          - zsh-completions
          - pkg-config
          - fzf
          - ripgrep
          - tig
          - bat
          - gitui
          - fzf
          - asdf
          - jq
          - zinit
          - neovim
          - tmux
          - tig
          - fd
          - alacritty
          - lsof
          - keychain
          - kubectl
          - kubectx
          - k9s
          - gh
          - git
          - git-delta
          - gnupg
          - pyenv
          - pyenv-virtualenv
          - gnu-sed  # for nvim-spectre
          - direnv
          - viddy

    - name: Clean homebrew
      command: "brew cleanup"
