---
- hosts: all
  tasks:
    - homebrew:
        state: presen
        name:
          - readline
          - wget
          - zsh
          - zsh-completions
          - pkg-config
          - fzf
          - ripgrep
          - tig
          - bat
          - lsd
          - jq
          - getantibody/tap/antibody
          - neovim
          - tmux
          - tig
          - fd
          - alacritty
          - htop
          - lsof
          - keychain
          - kubectl
          - kubectx
          - k9s
          - gh
          - git
          - git-delta
          - gnupg
          - pyenv
          - pyenv-virtualenv

    - name: Clean homebrew
      command: "brew cleanup"
