---
- hosts: all
  tasks:
    - name: Update homebrew
      command: "brew update"

    - homebrew_cask:
        name: "{{ item }}"
      with_items:
        - java
        - postgres
        - virtualbox
        - vagrant
        - vagrant-manager
        - ngrok
        - keka
        - iterm2
        - smartgit
        - tig

    - homebrew:
        name: "{{ item }}"
      with_items:
        - node
        - heroku
        - python
        - python3
        - ruby
        - elixir
        - docker
        - docker-compose
        - ctags
        - readline
        - wget
        - zsh
        - zsh-completions
        - zsh-syntax-highlighting
        - pkg-config
        - fzf
        - ripgrep

    - homebrew:
        update_homebrew: yes
        upgrade_all: yes

    - name: Configure fzf
      command: "$(brew --prefix)/opt/fzf/install"

    - name: Clean homebrew
      command: "brew cleanup"

    - name: Clean homebrew cask
      command: "brew cask cleanup"

    - npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - yarn
        - n
        - react-native-cli
        - nodemon
