---
- hosts: all
  tasks:
    - homebrew_tap:
        name: d12frosted/emacs-plus

    - homebrew_cask:
        name:
          - java
          - postgres
          - ngrok

    - homebrew:
        name:
          - node
          - readline
          - wget
          - zsh
          - zsh-completions
          - pkg-config
          - fzf
          - ripgrep
          - tig
          - bat
          - lsd
          - jq
          - getantibody/tap/antibody
          - emacs-plus

    - name: Clean homebrew
      command: "brew cleanup"

    - npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - yarn
        - n
        - nodemon
