---

- hosts: localhost

  vars:
    myzsh: "alias myzsh='docker run --net host -it --rm \
            -v /tmp:/tmp \
            -v ~/.ssh:/home/.ssh/ \
            -v $HOME/myzsh/backups:/root/.vim/backups \
            -v $(pwd):/app \
            -w /app imamatory/dotfiles'"

  tasks:

    - lineinfile:
        dest: /host/home/.bashrc
        line: "{{ myzsh }}"
        regexp: "myzsh"
        state: present
