---
- hosts: all
  vars:
    config: ~/.bash_profile
    nvim_packer_path: ~/.local/share/nvim/site/pack/packer/start
  tasks:

    - file:
        src: "{{ playbook_dir }}/nvim"
        dest: ~/.config/nvim
        state: link

    - file:
        path: ~/.local/share/nvim/site/autoload
        state: directory
        recurse: Yes

    - name: Install vim plug
      shell: 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      args:
        creates: ~/.local/share/nvim/site/autoload/plug.vim

    - file:
        path: "{{ nvim_packer_path}}"
        state: directory
        recurse: Yes

    - name: Install packer.nivm
      git:
        repo: "https://github.com/wbthomason/packer.nvim"
        dest: "{{ nvim_packer_path}}/packer.nvim"
        version: master

    - name: Install vim deps
      shell: "nvim -E -s -V -u ~/.config/nvim/init.vim +PlugInstall +qall || true"

    - name: Install packer deps
      shell: "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'"
