---
- hosts: all
  vars:
    config: ~/.bash_profile
    nvim_packer_path: ~/.local/share/nvim/site/pack/packer/start
  tasks:

    - file:
        src: "{{ playbook_dir }}/nvim"
        dest: ~/.config/nvim
        state: link

    - file:
        path: ~/.local/share/nvim/site/autoload
        state: directory
        recurse: Yes

    - file:
        path: "{{ nvim_packer_path}}"
        state: directory
        recurse: Yes

    - name: Install packer.nivm
      git:
        repo: "https://github.com/wbthomason/packer.nvim"
        dest: "{{ nvim_packer_path}}/packer.nvim"
        depth: 1
        version: master

    - name: Install packer deps
      shell: "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'"
