---
- hosts: all
  vars:
    config: ~/.bash_profile
  tasks:

    - file:
        src: "{{ playbook_dir }}/files/tmux.conf"
        dest: ~/.tmux.conf
        state: link

    - apt: name=tmux state=latest
