---
- hosts: all

  roles:
    - tmux

  tasks:

    - file:
        dest: ~/.config/nvim
        state: directory

    - file:
        src: "{{ curdir }}/files/vimrc"
        dest: ~/.config/nvim/init.vim
        state: link

    - get_url:
        force: yes
        dest: ~/.config/nvim/autoload/plug.vim
        url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    - homebrew:
        name: "{{ item }}"
      with_items:
        - fzf

    - name: Configure fzf
      command: "$(brew --prefix)/opt/fzf/install"

