---
- hosts: all

  vars:
    git_user: imamatory
    git_email: imamatory@gmail.com
    term: xterm-256color

  tasks:
    - apt_repository:
        repo: ppa:neovim-ppa/stable
        state: present
        update_cache: yes
      become: yes

    - name: Upgrade all packages to the latest version
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: True

    - name: Install locales
      become: yes
      apt:
        name: locales
        state: latest
        install_recommends: false

    - name: Gen locale
      become: yes
      shell: locale-gen en_US.UTF-8

    - name: Install base packages
      become: yes
      apt:
        state: latest
        install_recommends: false
        name:
          - sudo
          - libfontconfig
          - ca-certificates
          - git
          - curl
          - wget
          - make
          - cmake
          - sudo
          - inotify-tools
          - openssl
          - openssh-client
          - cargo
          - xz-utils
          - libfontconfig
          - python

    - name: Install docker
      shell: "curl -fsSL get.docker.com | sh"
      args:
        creates: /usr/bin/docker

    - name: "Install docker-compose"
      become: yes
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: "/usr/local/bin/docker-compose"
        mode: 0755

    - name: Install exa
      shell: "cargo install --force exa"
      args:
        creates: ~/.cargo/bin/exa

    - name: Install dev packages
      become: yes
      apt:
        state: latest
        install_recommends: false
        name:
          - tig
          - ruby
          - ruby-dev
          - nodejs
          - npm
          - neovim
          - tmux
          - zsh
          - jq
          - xclip
          - neovim

    - name: Install kitty-terminfo
      become: yes
      apt:
        deb: "http://ftp.de.debian.org/debian/pool/main/k/kitty/kitty-terminfo_{{ version }}_all.deb"
      vars:
        version: 0.13.3-1

    - name: Install ripgrep
      become: yes
      apt:
        deb: "https://github.com/BurntSushi/ripgrep/releases/download/{{ version }}/ripgrep_{{ version }}_amd64.deb"
      vars:
        version: 0.10.0

    - name: Install bat
      become: yes
      apt:
        deb: "https://github.com/sharkdp/bat/releases/download/v{{ version }}/bat_{{ version }}_amd64.deb"
      vars:
        version: 0.10.0

    - name: Install antibody
      become: yes
      shell: 'curl -sSL git.io/antibody | bash -s'
      args:
        creates: /usr/local/bin/antibody

    - name: Install fzf
      become: yes
      shell: |
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf \
        && ~/.fzf/install --key-bindings --update-rc --completion \
        && cp ~/.fzf/bin/fzf /usr/local/bin
      args:
        creates: /usr/local/bin/fzf
      environment:
        TERM: "{{ term }}"

    - name: Install oh-my-zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: ~/.oh-my-zsh/

    - name: Install spacemacs
      git:
        repo: "https://github.com/syl20bnr/spacemacs"
        dest: ~/.emacs.d

    - name: Setup git
      shell: |
        git config --global user.name {{ git_user }}
        git config --global user.email {{ git_email }}
        git config --global credential.helper cache

    - name: Setup shell
      become: yes
      shell: "chsh $USER -s $(which zsh);"
