---
- hosts: all
  vars:
    config: ~/.bash_profile
  tasks:

    - file:
        dest: ~/.config/nvim
        state: directory

    - file:
        src: "{{ playbook_dir }}/files/vimrc"
        dest: ~/.config/nvim/init.vim
        state: link

    - homebrew: name=neovim state=latest

    - file: path=~/.local/share/nvim/site/autoload state=directory recurse=Yes
      with_items:
        - autoload

    - get_url:
        force: yes
        dest: ~/.local/share/nvim/site/autoload/plug.vim
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
