set nocompatible

let $PATH = $PATH . ':' . expand('~/.local/bin') . ':' . '/usr/local/bin/'
let $LANG = 'en'

let g:python3_host_prog = '~/.pyenv/shims/python3'

lua require('init')

let mapleader = "\<Space>"

let test#strategy = "dispatch"
let test#javasctipt#runner = "jest"
let test#python#pytest#options = '--reuse-db'

nnoremap <silent> <Leader>tf :TestFile<CR>
nnoremap <silent> <Leader>tn :TestNearest<CR>
nnoremap <silent> <Leader>ts :TestSuite<CR>
nnoremap <silent> <Leader>tl :TestLast<CR>
nnoremap <silent> <Leader>tv :TestVisit<CR>

" Configure backspace so it acts as it should act
set backspace=eol,start,indent

" enhanced command completion
set wildmenu

set autoindent

" set visualbell
set completeopt=noinsert,menuone,noselect

set nowrap
set number
set hlsearch
set ignorecase
set smartcase

set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

set splitbelow
set splitright

if has('mouse')
  set mouse=a
endif

set cursorline

" Don't redraw while executing macros (good performance config)
set lazyredraw
set ttyfast

set shortmess+=at

" Turn backup off, since most stuff is in SVN, git et.c anyway...
set nowb
set noswapfile

" do incremental
set incsearch
" MAGIC LIVE SUBSTITUTE REPLACE SEARCH
set inccommand=nosplit

set cmdheight=1
" set scrolloff=3
set showcmd       " display incomplete commands
set autowrite     " Automatically :write before running commands

syntax on
filetype plugin indent on

" THEME

" colorscheme jellybeans
" let g:jellybeans_background_color_256='NONE'
" let g:jellybeans_use_term_background_color = 1
" let g:airline_theme='badwolf'


" supress error during setup
" silent! colorscheme material
silent! colorscheme catppuccin-frappe

" color dracula

let vimDir = '$HOME/.vim'
let &runtimepath.=','.vimDir

" ================ Persistent Undo ==================
" Keep undo history across sessions, by storing in file.
" Only works all the time.
if has('persistent_undo')
  let myUndoDir = expand(vimDir . '/undodir')
  call system('mkdir ' . vimDir)
  call system('mkdir ' . myUndoDir)
  let &undodir = myUndoDir
  set undofile
endif

let g:easytags_async = 1
let g:alchemist_iex_term_size = 15
let g:alchemist_iex_term_split = 'split'
let g:alchemist_tag_disable = 1

augroup au_common
  au!

  au BufWritePost init.vim,.vimrc source %
  " au BufWritePost *.re,*.rei :ReasonPrettyPrint

  " Automatically removing all trailing whitespace
  au BufWritePre * :%s/\s\+$//e

  au BufRead,BufNewFile {.babelrc,.eslintrc} set ft=json
augroup END

" augroup filetype_detect
"   autocmd BufNewFile,BufRead *.pug setlocal filetype=pug
" augroup END

vmap <C-_> gc
nmap <C-_> gcc

" select all text
nmap <C-a> ggVG<CR>

" nnoremap <Leader>o :CtrlP<CR>
nnoremap <Leader>s :w<CR>
nnoremap <Leader>w :w<CR>

" noremap <F3> :ALEFix<CR>
noremap <F5> :e<CR>
nmap <F8> :TagbarToggle<CR>

" vmap <Tab> >gv
" vmap <S-Tab> <gv
" nmap <Tab> >gv
" nmap <S-Tab> <gv

" let g:airline#extensions#tabline#enabled = 1
" let g:airline#extensions#tabline#buffer_idx_mode = 1
" nmap <leader>[ <Plug>AirlineSelectPrevTab
" nmap <leader>] <Plug>AirlineSelectNextTab

" Map ctrl-movement keys to window switching
" map <C-k> <C-w><Up>
" map <C-j> <C-w><Down>
" map <C-l> <C-w><Right>
" map <C-h> <C-w><Left>
" nnoremap <silent> <bs> <C-w><Left>

nmap <silent> // :nohlsearch<CR>
noremap ,hl :set hlsearch! hlsearch?<CR>

nmap <silent> cp "_ciw<C-R>"<Esc>

" disable ex mode
nnoremap Q <nop>

" set text wrapping toggles
nmap <silent> <leader>tw :set invwrap<CR>:set wrap?<CR>

nmap <leader><S-O> o<esc>kk<CR>

nnoremap Y y$

" search and replace
nnoremap <Leader>fr :%s///g<Left><Left>
vnoremap <Leader>fr "hy:%s/<C-r>h//gc<left><left><left>

" Search for selected text, forwards or backwards.
vnoremap <silent> * :<C-U>
  \let old_reg=getreg('"')<Bar>let old_regtype=getregtype('"')<CR>
  \gvy/<C-R><C-R>=substitute(
  \escape(@", '/\.*$^~['), '\_s\+', '\\_s\\+', 'g')<CR><CR>
  \gV:call setreg('"', old_reg, old_regtype)<CR>
vnoremap <silent> # :<C-U>
  \let old_reg=getreg('"')<Bar>let old_regtype=getregtype('"')<CR>
  \gvy?<C-R><C-R>=substitute(
  \escape(@", '?\.*$^~['), '\_s\+', '\\_s\\+', 'g')<CR><CR>
  \gV:call setreg('"', old_reg, old_regtype)<CR>

" Edit .vimrc
map <leader>vl :vsp $MYVIMRC<CR>

map <leader>vp :exe 'vsp'.stdpath('config').'/lua/plugins/init.lua'<CR>

" CtrlSF
nmap <leader>gg <Plug>CtrlSFPrompt
vmap <leader>gg <Plug>CtrlSFVwordPath
let g:ctrlsf_auto_focus = { "at": "start" }

nmap <silent> [b :bp<CR>
nmap <silent> ]b :bn<CR>

" vim-rooter
let g:rooter_patterns = ['Makefile','Rakefile', 'mix.exs', '.git/']

" nnoremap <silent> <Leader>b <cmd>lua require('telescope.builtin').buffers()<CR>
" nnoremap <silent> <Leader>h <cmd>lua require('telescope.builtin').oldfiles()<CR>
" nnoremap <silent> <Leader>o <cmd>lua require('telescope.builtin').git_files()<CR>
" nnoremap <silent> <Leader>fo <cmd>lua require('telescope.builtin').find_files()<CR>
" nnoremap <Leader>ft <cmd>lua require('telescope.builtin').filetypes()<CR>
" nnoremap <silent> <Leader>/ <cmd>lua require('telescope.builtin').live_grep()<CR>
" vnoremap <leader>/  <cmd>lua require('telescope.builtin').grep_string()<CR>
" nnoremap <leader>k  <cmd>lua require('telescope.builtin').grep_string()<CR>

nnoremap <silent> <Leader>b <cmd>lua require('fzf-lua').buffers()<CR>
nnoremap <silent> <Leader>h <cmd>lua require('fzf-lua').oldfiles()<CR>
nnoremap <silent> <Leader>o <cmd>lua require('fzf-lua').git_files()<CR>
nnoremap <silent> <Leader>fo <cmd>lua require('fzf-lua').find_files()<CR>
nnoremap <Leader>ft <cmd>lua require('fzf-lua').filetypes()<CR>
nnoremap <silent> <Leader>/ <cmd>lua require('fzf-lua').grep()<CR>
vnoremap <leader>/  <cmd>lua require('fzf-lua').grep_visual()<CR>
nnoremap <leader>k  <cmd>lua require('fzf-lua').grep_cword()<CR>

nnoremap <leader>xx <cmd>Trouble diagnostics<cr>
nnoremap <leader>xw <cmd>Trouble workspace_diagnostics<cr>
nnoremap <leader>xd <cmd>Trouble document_diagnostics<cr>
nnoremap <leader>xq <cmd>Trouble quickfix<cr>
nnoremap <leader>xl <cmd>Trouble loclist<cr>
nnoremap gR <cmd>TroubleToggle lsp_references<cr>

nmap <leader>mp <Plug>MarkdownPreview
nmap <leader>ms <Plug>MarkdownPreviewStop
nmap <leader>mt <Plug>MarkdownPreviewToggle

nnoremap <silent> <Leader>cd :Copilot disable<CR>
nnoremap <silent> <Leader>ce :Copilot enable<CR>
nnoremap <silent> <Leader>cr :Copilot restart<CR>

command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   "rg --column --line-number --no-heading --color=always --fixed-strings --smart-case --hidden --follow --glob '!.git/*' ".shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)

" Clipboard
" nmap <Leader>p :set paste<CR><esc>"+p: set nopaste<cr>
" nmap <Leader>P :set paste<CR><esc>o<Esc>"+p: set nopaste<cr>
" vmap <Leader>y "+y
" nnoremap Y y$

" Git fugitive
nnoremap <silent> <Leader>gl :Commits<CR>
nnoremap <silent> <Leader>ga :BCommits<CR>
nnoremap <silent> <Leader>gb :Git blame<CR>
nnoremap <silent> <Leader>gs :Gstatus<CR>
nnoremap <silent> <leader>gd :Gdiff<CR>
nnoremap <silent> <leader>gc :Gvdiffsplit!<CR>

" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)
" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

nmap <Leader>pi :call pry#insert()<CR>

nnoremap <tab> :NERDTreeFind<CR>
nmap <silent> <leader><leader> :NERDTreeToggle<CR>

let NERDTreeIgnore = ['\.pyc$']
let g:nerdtree_tabs_open_on_console_startup = 1
let NERDTreeMapJumpNextSibling='<C-N>'
let NERDTreeMapJumpPrevSibling='<C-O>'

let g:loaded_netrwPlugin = 1

" if hidden is not set, TextEdit might fail.
set hidden

" Some servers have issues with backup files, see #649
set nobackup
set nowritebackup

" Better display for messages
" set cmdheight=2

" You will have bad experience for diagnostic messages when it's default 4000.
" set updatetime=300

" don't give |ins-completion-menu| messages.
" set shortmess+=c

" always show signcolumns
set signcolumn=yes

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

" Remap for rename current word
" nmap <leader>rn <Plug>(coc-rename)

" Remap for format selected region
" xmap <leader>f  <Plug>(coc-format-selected)
" nmap <leader>f  <Plug>(coc-format-selected)

" augroup mygroup
"   autocmd!
"   " Setup formatexpr specified filetype(s).
"   autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
"   " Update signature help on jump placeholder
"   autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
" augroup end

" Remap for do codeAction of selected region, ex: `<leader>aap` for current paragraph
" xmap <leader>a  <Plug>(coc-codeaction-selected)
" nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap for do codeAction of current line
" nmap <leader>ac  <Plug>(coc-codeaction)
" Fix autofix problem of current line
" nmap <leader>qf  <Plug>(coc-fix-current)

" Create mappings for function text object, requires document symbols feature of languageserver.
" xmap if <Plug>(coc-funcobj-i)
" xmap af <Plug>(coc-funcobj-a)
" omap if <Plug>(coc-funcobj-i)
" omap af <Plug>(coc-funcobj-a)

" Use <C-d> for select selections ranges, needs server support, like: coc-tsserver
" nmap <silent> <C-d> <Plug>(coc-range-select)
" xmap <silent> <C-d> <Plug>(coc-range-select)

" Use `:Format` to format current buffer
" command! -nargs=0 Format :call CocAction('format')

" nnoremap <Leader>l :Format<CR>
" nnoremap <Leader>i :CocCommand python.sortImports<CR>

" Use `:Fold` to fold current buffer
" command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" use `:OR` for organize import of current buffer
" command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Add status line support, for integration with other plugin, checkout `:h coc-status`
" set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

" Surround options. Avoid capturing of leading whitespaces.
nmap ysa' ys2i'
nmap ysa" ys2i"
nmap ysa` ys2i`

" call coc#config('python', {'pythonPath': $PYENV_VIRTUAL_ENV})
