return {
  -- Core plugins
  { "tpope/vim-sensible" },
  { "tpope/vim-surround" },
  { "tpope/vim-repeat" },
  { "nathanaelkane/vim-indent-guides" },
  { "scrooloose/nerdtree" },
  { "vim-airline/vim-airline" },
  { "vim-airline/vim-airline-themes" },
  { "catppuccin/nvim", name = "catppuccin" },
  { "xolox/vim-misc" },
  { "terryma/vim-multiple-cursors" },
  { "tpope/vim-commentary" },
  { "tpope/vim-abolish" },
  { "tpope/vim-fugitive" },
  { "michaeljsmith/vim-indent-object" },
  { "Chiel92/vim-autoformat" },
  { "imamatory/leader-clipboard" },
  { "digitaltoad/vim-pug" },
  { "elzr/vim-json" },
  { "AndrewRadev/splitjoin.vim" },
  { "ap/vim-css-color" },
  { "hhsnopek/vim-sugarss" },
  { "slashmili/alchemist.vim" },
  { "ekalinin/Dockerfile.vim" },
  { "editorconfig/editorconfig-vim" },
  { "dyng/ctrlsf.vim" },
  { "junegunn/vim-easy-align" },
  { "vtm9/vim-dispatch" },
  { "janko-m/vim-test" },
  { "airblade/vim-rooter" },
  { "jszakmeister/vim-togglecursor" },
  { "vtm9/vim-pry" },
  { "sheerun/vim-polyglot" },
} 